### ISSUE TITLE
ghooks not found!

### ISSUE THREAD

**Issue by HackPoint** [ghooks-org/ghooks#78] opened 2016-04-05 16:06 UTC
# I'm receiving this even when I installed everything even globally.

`ghooks not found!
Make sure you have it installed on your "node_modules".
Skipping git hooks.`

```
package.json
"config": {
    "ghooks": {
      "commit-msg": "validate-commit-msg",
      "post-merge": "npm install"
    }
  }
```

**Comment by kentcdodds** [comment] 2016-04-05 16:08
You definitely don't want to install this globally. Maybe if there's a way to detect this we could throw a helpful error indicating that.

Could you give us more information? Dig a little bit to try and see what's going on?

**Comment by ta2edchimp** [comment] 2016-04-05 18:15
`ghooks` should have worked when installed globally, prior to version `1.2.0` (released some hours ago).
The way its core functionality is included now, supports being used from within git submodules and when altering the paths' structure by using git worktrees (as both of these ways heavily change the relation of the hooks' path to their git repo's files); but the downside is, there's no simple `require('ghooks')` anymore in the hooks themselves (that one provided a fallback to a globally installed ghooks, when not installed locally).

What I propose is one of the following:

- Generally `npm install` things like ghooks locally. `npm i -D ghooks` would do this as a development dependency for a particular package.

or 

- Use `ghooks` version `1.1.1` when you don't want to install it locally to your package (or even `1.0.3` if you don't like it to exit with an error when ghooks have not been found).

---

@kentcdodds I'd happily make another PR with a fallback, trying to require a globally installed ghooks, while printing an info that it's considered best practice to install it locally. (I also have another unfinished change that would allow to configure whether or not to exit with an error if ghooks has not been found.)
And btw. sorry for adding so much noise to this project :disappointed:

**Comment by HackPoint** [comment] 2016-04-05 19:06
I actually tried to install it locally with '''git i -D''' still the same result. Tried latest and 1.0.2v

**Comment by ta2edchimp** [comment] 2016-04-05 19:19
I guess you mean `npm i -D` ... on what version of node and npm are you testing?

**Comment by ta2edchimp** [comment] 2016-04-05 22:09
Do you have this particular project publicly online, here on github for example?

**Comment by gtramontina** [comment] 2016-04-05 23:18
@HackPoint, could you please paste us the result of running the following in the root of your project?

```sh
npm -v; node -v; npm ls | grep ghooks
```

---
@ta2edchimp:

> And btw. sorry for adding so much noise to this project

Please, don't stop! Your contributions are really valuable! :+1::beers:

**Comment by HackPoint** [comment] 2016-04-06 05:16
> npm -v; node -v; npm ls | grep ghooks
```
3.8.5
v5.7.1
+-- ghooks@1.0.3
```

### It was after testing the whole range of versions

**Comment by ta2edchimp** [comment] 2016-04-06 06:22
That's totally strange. Using `ghooks@1.0.3` it should work even when installed globally.

- Are you using `git submodules` or different worktrees?
- On what `git --version` are you?
- What operating system are you on?
- Could you please, in a different, completely empty directory, try the following:
  - `git init`
  - `npm init -y`
  - `npm i -D ghooks`
  - add a `pre-commit` hook to package.json, sth simple like `echo \"SOMETHING\"`
  - make a test commit, and report if it worked?

**Comment by HackPoint** [comment] 2016-04-06 06:34
> Git version
$ git --version
git version 2.7.2

Ok, I will try to run it without anything in the project, I will update you about the progress.
Tell me could I print the Exception stack why this could happen, if ###yes### tell me where and how to run it?

**Comment by ta2edchimp** [comment] 2016-04-06 06:57
On `1.2.0` it's not really an Exception that would bubble up, but rather a failing/rejected Promise internally. It's an Exception prior to `1.2.0` that gets catched at the very beginning of the git hook's file.

ghooks < 1.2.0
You could just comment out the `try`/`catch` line for example in `.git/hooks/pre-commit` and make a test commit. The stack trace should be printed to command line.

ghooks @ 1.2.0
You _could_ use [`devtool`](https://www.npmjs.com/package/devtool) to run it using a Chrome-like dev tools / inspector, it's what I'd do in this case. If you do this, change the first line of the git hook's file to be tested to read `#!/usr/bin/env devtool` instead of `node`. After that you should get an output in devtool's console that you can expand to see where it's failing originally, just like an ordinary exception in a browser's dev tools.

**Comment by ta2edchimp** [comment] 2016-04-06 07:00
What os are you on?

**Comment by HackPoint** [comment] 2016-04-06 07:03
El Capitan 10.11.3

**Comment by ta2edchimp** [comment] 2016-04-13 21:49
@HackPoint do you have a project publicly available where we/I may take a look into this issue? I wasn't yet able to reproduce this -- that is, except when liberatley removing ghooks from `node_modules`.

**Comment by Prophet32j** [comment] 2016-06-09 16:42
+1 for this. We are also experiencing this same issue.Also installed locally in devDependencies.
package.json

    "ghooks": "^1.2.3"
    "config": {
        "ghooks": {
           "pre-commit": "npm run lint",
           "pre-push": "npm test"
        }
    }

**Comment by Prophet32j** [comment] 2016-06-09 19:14
@ta2edchimp is there a requirement that the .git/ folder be on the same level as the node_modules/ folder? 
Reason I ask is we have our UI project embedded in our web app project. It's not a submodule. It sits a level below the root project folder where .git/ lives. Would that cause an error?

**Comment by Prophet32j** [comment] 2016-06-09 19:24
Ok. So I created an NPM project at our root to test this theory. I did the following:

    npm init
    npm i -D ghooks

In package.json

    ...
    "config": {
      "ghooks": {
        "pre-commit": "echo \"HELLO WORLD\""
      }
    }

Sure enough, I get `HELLO WORLD` in the console.

**Comment by ta2edchimp** [comment] 2016-06-10 08:48
>@ta2edchimp is there a requirement that the .git/ folder be on the same level as the node_modules/ folder? 
Reason I ask is we have our UI project embedded in our web app project. It's not a submodule. It sits a level below the root project folder where .git/ lives. Would that cause an error?

That should work without error, as `ghooks` traverses the tree up, to find the `.git` folder. A special case is using submodules or git's worktree functionality, but we also take care of that.

---

I really don't get it why the error message mentioned in the OP should be yielded, all fiddles I did with any setup I could think of, worked successfully.
@Prophet32j @HackPoint If anyone of you can provide a link to a repo with a configuration that runs into this error, that would be really really useful ... I'm feeling completely blind here :(

**Comment by Prophet32j** [comment] 2016-06-10 13:31
I will try and set up a project like how we have it internally. Due to company policy I have to be careful on how I approach this.

**Comment by ta2edchimp** [comment] 2016-06-10 13:48
I'd appreciate any kind of hint, you could provide. Maybe a simple "anonymous" description of the corresponding folder / project structure would be sufficient to begin with investigating.

**Comment by larrifax** [comment] 2016-06-10 14:20
I'm getting the same error as the OP using a folder structure that looks like this:
```
Project/
  .git/
  src/
    Project.Web/
      node_modules/
      package.json
```
The `package.json`-file (in `Project.Web/`) looks like this (excerpt):
```
{
  "version": "1.0.0",
  "config": {
    "ghooks": {
      "pre-commit": "gulp lint"
    }
  },
  "devDependencies": {
    "ghooks": "1.2.3"
  }
}
```
Output from `npm -v; node -v; npm ls | grep ghooks`:
```
3.8.9
v6.2.1
+-- ghooks@1.2.3
```

To me, it seems that the `pre-commit`-hook generated by `ghooks` falls back to using `require("ghooks")` when there is no mention of `worktree` in git's `config`-file that sits in my `Project`-folder. As far as I can see, git hooks are run with CWD set to the project root, which causes it to fail since there is no `node_modules` in that directory.

**Comment by ta2edchimp** [comment] 2016-06-10 15:49
Yep, that seems to be the cause. 👍 

A PR would be highly appreciated 😉
Otherwise I'll try to get my hands on this in the coming days.

---

@HackPoint @Prophet32j would this apply to your setup as well?

**Comment by Prophet32j** [comment] 2016-06-10 22:18
Yes this is our setup as well. I was working on a PR to apply a new variable to the template file. I ran out of time right now, but hopefully I can get some more time later this evening.

If anyone can finish, the new variable will be populated with the node_modules path at install time instead of having to be found during execution. Execution would require some sort of recursive directory read.

@ta2edchimp @gtramontina what do you think about that?

**Comment by Prophet32j** [comment] 2016-06-11 14:45
@ta2edchimp @gtramontina I have a working fork for our project structure [prophet32/ghooks](https://github.com/Prophet32j/ghooks)

Not all the tests are passing because I am not passing `__dirname`. Instead I pass the derived node_modules path for the project. I didn't want to fix the tests, because I wasn't sure if this is the correct direction you wanted to go.

Can you take a look, pull it down and determine if this is right?

**Comment by gtramontina** [comment] 2016-07-04 00:29
@HackPoint @Prophet32j @larrifax Can you please confirm that this issue has been fixed on [v1.3.0](https://github.com/gtramontina/ghooks/releases/tag/v1.3.0)?

**Comment by illyashevchenko** [comment] 2016-07-04 11:27
It seems to be working on MacOS and not working in Windows - still "ghooks not found error"
![image](https://cloud.githubusercontent.com/assets/8465842/16559131/6b678300-41f3-11e6-9a44-b941cc37443a.png)

**Comment by KristianSelnas** [comment] 2016-07-04 11:49
This was reported in #108 and fixed in #114. Just lit back and wait for next release :-)

**Comment by kentcdodds** [comment] 2016-07-04 12:04
Merged and released. Let us know if it's working now.

**Comment by KristianSelnas** [comment] 2016-07-04 12:25
The .replace(/\\/g, '\\')) in hook.template.js does't seem to work. I still
produces unescaped paths in the generated hook-files. (I've deleted all
hooks and the node_modules/ghooks folder and installed it again.)

I suck at regex, but should it perhaps be .replace(/\\/g, '\\\\'))?


-Kristian

**Comment by ta2edchimp** [comment] 2016-07-04 12:33
Dammit... of course it must be `replace(/\\/g, '\\\\'))`. The other one just replaces one backslash by another single backslash.
And I even thought about writing some kind of test for the Windows path separator ... m(

Would you make a PR with that exact change? I'm heading to the airport right now and am not near any computer for two weeks :disappointed:

**Comment by KristianSelnas** [comment] 2016-07-04 12:36
Will do :-)

**Comment by gtramontina** [comment] 2016-07-04 13:11
> I'm heading to the airport right now and am not near any computer for two weeks

@ta2edchimp Good for you! You should've been smiling… 😄 

Thanks for stepping up, @KristianSelnas 🍻

**Comment by KristianSelnas** [comment] 2016-07-04 13:20
Yay! It works 😀

The config, however, seems to be running relative to the git root and not
relative to where the package.json is. This might be intentional, but I
don't know how intuitive it is. When I add the following config, I sort of
expect it to run relative to where this package.json is.

"config": {
  "ghooks": {
    "pre-commit": "gulp lint"
  }
}


-Kristian

**Comment by gtramontina** [comment] 2016-07-04 13:38
🎉🎉 Thanks a lot!
> This might be intentional, but I
don't know how intuitive it is. When I add the following config, I sort of
expect it to run relative to where this package.json is.

As you said, it is a bit counter-intuitive, although it sort of makes sense if you look at it from the git hook perspective. Anyway, it might worth mentioning that behaviour in the README…

**Comment by kevinSuttle** [comment] 2016-10-11 19:17
Still getting this on Node 6.7.

**Comment by kentcdodds** [comment] 2016-10-11 19:20
I'm recommending people switch to [husky](http://npm.im/husky).

**Comment by kevinSuttle** [comment] 2016-10-11 19:25
Ok, but in the meantime, is nuking and re-initializing the git repo the only solution?

**Comment by kentcdodds** [comment] 2016-10-11 19:27
I don't know that, sorry.

**Comment by miguelsolano** [comment] 2017-01-19 07:57
I know this is super late @kevinSuttle (might still be useful to other people though), but typically if you cd into the `.git` folder and just remove the hooks dir and add a blank `hooks` dir and install husky, you can migrate over. Of course, you'll have to rewrite your hooks, but thats better than nuking a git repo and reinitializing.

**Comment by jhabdas** [comment] 2017-06-19 09:23
No significant activity in over 6 months. Closing. Please open a new issue if needed.

**Closed by jhabdas** 2017-06-19 09:23 UTC
