### ISSUE TITLE
Failed at the ghooks@1.3.2 install script 'node ./bin/module-install'. in Windows

### ISSUE THREAD

**Issue by git-anurag** [ghooks-org/ghooks#133] opened 2016-07-20 10:37 UTC
Following is the erros:

> ghooks@1.3.2 install C:\xampp\htdocs\qui_1\q-municate-web\node_modules\ghooks
> node ./bin/module-install

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! file C:\Windows\system32\cmd.exe,;C:\Program Files (x86)\Git\bin;C:\Program Files (x86)\Git\cmd
npm ERR! path C:\Windows\system32\cmd.exe,;C:\Program Files (x86)\Git\bin;C:\Program Files (x86)\Git\cmd
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\Windows\system32\cmd.exe,;C:\Program Files (x86)\Git\bin;C:\Program Files (x86)\Git\cmd

npm ERR! ghooks@1.3.2 install: `node ./bin/module-install`
npm ERR! spawn C:\Windows\system32\cmd.exe,;C:\Program Files (x86)\Git\bin;C:\Program Files (x86)\Git\cmd ENOENT
npm ERR!
npm ERR! Failed at the ghooks@1.3.2 install script 'node ./bin/module-install'.
npm ERR! This is most likely a problem with the ghooks package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/module-install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ghooks
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls ghooks
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\qui_1\q-municate-web\npm-debug.log

**Comment by ta2edchimp** [comment] 2016-07-20 11:28
You installed it regularly via `npm install [...] ghooks` as a dependency?

**Comment by git-anurag** [comment] 2016-07-20 11:30
I have run the command `grunt build`

**Comment by ta2edchimp** [comment] 2016-07-20 12:08
Is [QuickBlox/q-municate-web](https://github.com/QuickBlox/q-municate-web) the project you try to build? If yes, I'll try it out myself later today.

**Comment by git-anurag** [comment] 2016-07-20 12:26
Yes I am trying to build  [QuickBlox/q-municate-web](https://github.com/QuickBlox/q-municate-web).
The previously mentioned error I am getting because of `npm install` and while execute `grunt build` I am getting following error Warning: Couldn't find the `compass.BAT` binary. Make sure it's installed and in your $PATH Use --force to continue.

**Comment by ta2edchimp** [comment] 2016-07-20 12:28
Please see https://github.com/QuickBlox/q-municate-web/issues/5 (especially the [last comment](https://github.com/QuickBlox/q-municate-web/issues/5#issuecomment-120974082)), seems related.

**Comment by git-anurag** [comment] 2016-07-20 13:12
ok but I am getting error related to ghooks also as mentioned.

**Comment by ta2edchimp** [comment] 2016-07-20 13:27
As I'm not able to reproduce it (it seems to me that `npm` is complaining about `node ./bin/module-install` not being found, `ENOENT`), could you please try the following:

1. manually remove the devDependency ghooks ([`q-municate-web/package.json` line 8](https://github.com/QuickBlox/q-municate-web/blob/master/package.json#L8))
2. run `npm install`  
_**(please ensure you run your command prompt as Administrator, as instructed [here](https://github.com/QuickBlox/q-municate-web#5-setup-environment))**_
3. re-install ghooks as a devDependency afterwards via `npm install -D ghooks`

and see, what happens? If it, again, does not work, please report back any warnings or error messages, especially at which of the above steps they occurred.

**Comment by git-anurag** [comment] 2016-07-20 13:34
I run the following command : 

`$ npm install -D ghooks`

npm WARN package.json q-municate@1.5.0 No repository field.
npm WARN package.json q-municate@1.5.0 No license field.
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!

> ghooks@1.3.2 install C:\xampp\htdocs\qui_1\q-municate-web\node_modules\ghooks
> node ./bin/module-install

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-D" "ghooks"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! file C:\Windows\system32\cmd.exe,;C:\Program Files (x86)\Git\bin;C:\Program Files (x86)\Git\cmd
npm ERR! path C:\Windows\system32\cmd.exe,;C:\Program Files (x86)\Git\bin;C:\Program Files (x86)\Git\cmd
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\Windows\system32\cmd.exe,;C:\Program Files (x86)\Git\bin;C:\Program Files (x86)\Git\cmd

npm ERR! ghooks@1.3.2 install: `node ./bin/module-install`
npm ERR! spawn C:\Windows\system32\cmd.exe,;C:\Program Files (x86)\Git\bin;C:\Program Files (x86)\Git\cmd ENOENT
npm ERR!
npm ERR! Failed at the ghooks@1.3.2 install script 'node ./bin/module-install'.
npm ERR! This is most likely a problem with the ghooks package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/module-install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ghooks
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls ghooks
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by ta2edchimp** [comment] 2016-07-20 14:27
`C:\xampp\htdocs\qui_1\q-municate-web\npm-debug.log` is a file I'd be highly interested in.
Could you please upload its content somewhere publicly available (a [Gist here on GitHub](https://gist.github.com/) or [pastebin](http://pastebin.com/))?

You may also include it here in the discussion, but as it could be grown huge, please enclose it like the following:

```
<details>
your npm-debug.log content here
</details>
```

**Comment by git-anurag** [comment] 2016-07-20 14:34
[npm-debug.log](https://gist.github.com/git-anurag/64673b35c06331ccd93c06dd4b2c7f0c)

**Comment by ta2edchimp** [comment] 2016-07-20 16:46
I absolutely don't get it right now why this is not working.

Are you planning on developing on [QuickBlox/q-municate-web](https://github.com/QuickBlox/q-municate-web) or just using it?

* **If you're only planning on using it**, you don't need the git hooks setup using `ghooks` and could leave it out of `package.json`, running `npm install` afterwards.

* **If you're planning on developing on it**, I would suggest opening an issue on their repo too (and linking back to this issue) and proceed the above procedure by trying out one or more of the following steps:
  * try installing `ghooks` via `npm install -D --ignore-scripts ghooks` and running `npm explore ghooks -- npm run install` afterwards.
  * try again with updated versions of node and npm

As of now, your system seems to not being able to find what's needed to run ghooks' postinstall script (`ENOENT` Error No Entry aka File (or Folder) Not Found) and at the moment, the reason is absolutely unclear to me.

**Comment by jhabdas** [comment] 2017-06-19 09:20
This is quite old. Closing. Please open a new issue and link back here if issue persists.

**Closed by jhabdas** 2017-06-19 09:20 UTC
